# Generated by Django 4.2.23 on 2025-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_name',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='semster',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='date',
        ),
        migrations.AddField(
            model_name='classroom',
            name='roomNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='start',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='to',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
