# Generated by Django 4.2.23 on 2025-09-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0002_rename_class_name_classroom_classname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='ClassroomTable',
        ),
    ]
