# Generated by Django 4.2.23 on 2025-09-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0004_complainttable_delete_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.studenttable')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
