# Generated by Django 4.2.23 on 2025-09-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0006_departmenttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachertable',
            old_name='subject',
            new_name='email',
        ),
        migrations.AddField(
            model_name='teachertable',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teachertable',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teachertable',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.logintable'),
        ),
    ]
