# Generated by Django 5.2.7 on 2025-10-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0007_rename_subject_teachertable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.logintable'),
        ),
    ]
