# Generated by Django 4.2.26 on 2025-11-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0008_studenttable_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachertable',
            old_name='password',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='teachertable',
            name='username',
        ),
        migrations.AddField(
            model_name='teachertable',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
