# Generated by Django 4.2.26 on 2025-11-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0009_rename_password_teachertable_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=30, null=True)),
                ('sem', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.departmenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('DEPARTMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.departmenttable')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('CLASS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.classtable')),
                ('slot_10_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_10_11', to='mobilesilentapp.subjecttable')),
                ('slot_11_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_11_12', to='mobilesilentapp.subjecttable')),
                ('slot_1_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_1_2', to='mobilesilentapp.subjecttable')),
                ('slot_2_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_2_3', to='mobilesilentapp.subjecttable')),
                ('slot_3_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_3_4', to='mobilesilentapp.subjecttable')),
                ('slot_9_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_9_10', to='mobilesilentapp.subjecttable')),
            ],
        ),
    ]
