# Generated by Django 4.2.26 on 2025-11-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0010_classtable_subjecttable_timetable1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable1',
            old_name='slot_1_2',
            new_name='slot_12_1',
        ),
        migrations.RemoveField(
            model_name='timetable1',
            name='slot_3_4',
        ),
    ]
