# Generated by Django 4.2.26 on 2025-11-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0011_rename_slot_1_2_timetable1_slot_12_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable1',
            name='slot_12_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_12_1', to='mobilesilentapp.subjecttable'),
        ),
    ]
