# Generated by Django 4.2.26 on 2025-11-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0012_alter_timetable1_slot_12_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='class_name',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='CLASS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.classtable'),
        ),
    ]
