# Generated by Django 4.2.26 on 2025-12-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0013_remove_studenttable_class_name_studenttable_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertable',
            name='department',
        ),
        migrations.AddField(
            model_name='teachertable',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilesilentapp.departmenttable'),
        ),
    ]
