# Generated by Django 4.2.26 on 2025-12-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesilentapp', '0014_remove_teachertable_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertable',
            name='class_name',
        ),
    ]
